version: v1.0

vector_store:
  provider: qdrant
  persistence: disk
  config:
    host: localhost
    port: 6333

graph_store:
  provider: neo4j
  persistence: disk
  config:
    uri: bolt://localhost:7687
    user: neo4j
    password: your_password

event_store:
  provider: mongo
  persistence: disk
  config:
    uri: mongodb://localhost:27017
    db: contextzero
    collection: events

time_series_store:
  provider: timescaledb
  persistence: disk
  config:
    uri: postgresql://user:pass@localhost:5432/contextzero

prompt:
  fact_extraction: null
  memory_update: null
  procedural_memory: null
